#!/bin/sh
 
upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((${upSeconds}%60))
mins=$((${upSeconds}/60%60))
hours=$((${upSeconds}/3600%24))
days=$((${upSeconds}/86400))
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
 
# get the load averages
read one five fifteen rest < /proc/loadavg
 
echo "
       [1;36m`date +"%A, %e %B %Y, %r"`
           `uname -srm`[0m

[1;32mOS.................:[0m `cat /etc/os-release |grep PRETTY|awk -F '"' {'print $2'}`
[1;32mUptime.............:[0m ${UPTIME}
[1;32mMemory.............:[0m `cat /proc/meminfo | grep MemFree | awk {'print $2'}`kB (Free) / `cat /proc/meminfo | grep MemTotal | awk {'print $2'}`kB (Total)
[1;32mLoad Averages......:[0m ${one}, ${five}, ${fifteen} (1, 5, 15 min)
[1;32mRunning Processes..:[0m `ps ax | wc -l | tr -d " "`
[1;32mLAN1 IP Addresses.......:[0m `ip a | grep 'global eth0' | awk '{print $2}'`
[1;32mLAN2 IP Addresses.......:[0m `ip a | grep 'global eth1' | awk '{print $2}'`
$(tput sgr0)
"
